import type { Discipline } from '@/types/content'

export const po1: Discipline = {
  slug: 'po1',
  title: 'Pesquisa Operacional I',
  subtitle: 'Videoaulas e materiais da disciplina de PO I.',
  lessons: [
    { id: 'aula-1', number: 1, title: 'Aula 1: Introdução à Pesquisa Operacional',
      description: 'Aula introdutória sobre os conceitos básicos de Pesquisa Operacional e Programação Linear.',
      topics: 'Definição de PO, Fases de um estudo em PO e Introdução a Programação Linear.',
      videos: [{ title: 'Aula completa', youtubeId: 'v5KRSzU2E4U' }],
      materials: [{ title: 'Slides - Introdução a PO', url: '/materiais/po1/introducao-po.ppt' }] },
    { id: 'aula-2', number: 2, title: 'Aula 02: Resolução Gráfica de PPL',
      description: 'Aprendemos a resolver problemas de duas variáveis de forma gráfica e damos os primeiros passos no método Simplex.',
      topics: 'Resolver PPLs com duas variáveis de decisão pelo método gráfico.',
      videos: [], materials: [] },
    { id: 'aula-3', number: 3, title: 'Aula 03: Software para resolver PPLs',
      description: 'Aprender a utilizar softwares na resolução de PPLs: SOLVER, LINDO e LINGO',
      topics: 'PPLs, SOLVER, LINDO e LINGO',
      videos: [
        { title: 'SOLVER pt. 1', youtubeId: 'pNNsL4GzNg8' },
        { title: 'SOLVER pt. 2', youtubeId: 'IMG0vcnQeX0' },
        { title: 'LINDO', youtubeId: 'vFSXrhpg3r8' },
        { title: 'LINGO', youtubeId: 'BCnLTTcSDGg' },
      ], materials: [] },
    { id: 'aula-4', number: 4, title: 'Aula 04: Equivalência entre PPLs e Modelagem Matemática de PPL',
      description: 'Aprender a fazer a formulação de problemas de programação linear',
      topics: 'Equivalencia entre PPLs e Modelagem Matemática de PPL',
      videos: [
        { title: 'Equivalencia', youtubeId: 'xQtosRABD2E' },
        { title: 'Modelagem', youtubeId: 'mw9Mpe-PvZ4' },
      ],
      materials: [
        { title: 'Slides - Equivalência', url: '/materiais/po1/equivalencia-ppls.pptx' },
        { title: 'Slides - Modelagem', url: '/materiais/po1/modelagem-matematica-ppls.pptx' },
      ] },
    { id: 'aula-5', number: 5, title: 'Aula 05: Algoritmo Simplex',
      description: 'Aprender resolução de PPL pelo algoritmo simplex.',
      topics: 'Algoritmo Simplex, Tabelas Simplex, Método Simplex.',
      videos: [{ title: 'Aula completa', youtubeId: 'JTcUGbG8pg0' }],
      materials: [{ title: 'Slides - Simplex', url: '/materiais/po1/simplex.pptx' }] },
    { id: 'aula-6', number: 6, title: 'Aula 06: Método Big-M',
      description: 'Aprender método para resolver qualquer tipo de PPL.',
      topics: 'Método Big-M, PPLs, Resolução de PPLs.',
      videos: [{ title: 'Aula completa', youtubeId: 'gQP8WfzwFU8' }],
      materials: [{ title: 'Slides - Big-M', url: '/materiais/po1/big-m.pptx' }] },
    { id: 'aula-7', number: 7, title: 'Aula 07: Dualidade',
      description: 'Teoria da dualidade e seus teoremas.',
      topics: 'Dualidade, Teoria da Dualidade, Teoremas da Dualidade, TFC.',
      videos: [
        { title: 'Dualidade pt.1', youtubeId: 'LkJlsxEtaE4' },
        { title: 'Dualidade pt.2 - Relações entre o Primal e o Dual', youtubeId: 'RU10F3dU0Xo' },
        { title: 'Algoritmo Simplex Dual', youtubeId: 'i2fcz5FRRos' },
        { title: 'Exemplos de Dualidade', youtubeId: '7Gc2aiE7M7U' },
      ],
      materials: [
        { title: 'Slides - Dualidade Parte 1', url: '/materiais/po1/dualidade-parte-1.pptx' },
        { title: 'Slides - Dualidade Parte 2', url: '/materiais/po1/dualidade-parte-2.pptx' },
      ] },
    { id: 'aula-8', number: 8, title: 'Aula 08: Interpretação Econômica da Dualidade e Simplex Dual',
      description: 'Compreende o significado de dualidade e o algoritmo Simplex Dual.',
      topics: 'Dualidade, Interpretação Econômica, Simplex Dual.',
      videos: [{ title: 'Aula completa', youtubeId: 'i2fcz5FRRos' }], materials: [] },
    { id: 'aula-9', number: 9, title: 'Aula 09: Análise de Sensibilidade e Pós-otimização Com Solver',
      description: 'Analisar alterações no PPL e usar o software Solver para fazer análise de sensibilidade.',
      topics: 'Análise de Sensibilidade, Pós-otimização, Software de PPL.',
      videos: [
        { title: 'Análise de Sensibilidade e Pós-otimização pt.1', youtubeId: 'Z-duqQJFa-4' },
        { title: 'Análise de Sensibilidade e Pós-otimização pt.2', youtubeId: 'C0tpwFouwMA' },
        { title: 'Análise de Sensibilidade e Pós-otimização pt.3', youtubeId: 'nHPLI1uM0ks' },
      ],
      materials: [{ title: 'Slides - Análise de Sensibilidade', url: '/materiais/po1/analise-de-sensibilidade-2025.pptx' }] },
    { id: 'aula-10', number: 10, title: 'Aula 10: Problema do Transporte e Designação',
      description: 'Aprender o problema de transporte e o método húngaro para resolver o problema da designação.',
      topics: 'Problema do Transporte, Problema da Designação, Método Húngaro.',
      videos: [{ title: 'Aula completa', youtubeId: 't2vUhtY1rbo' }], materials: [] },
  ],
}
