import type { Discipline } from '@/types/content'

export const po2: Discipline = {
  slug: 'po2',
  title: 'Pesquisa Operacional II',
  subtitle: 'Videoaulas e materiais da disciplina de PO II.',
  lessons: [
    { id: 'aula-1', number: 1, title: 'Aula 1: Introdução à Pesquisa Operacional',
      description: 'Aula introdutória sobre os conceitos básicos de Pesquisa Operacional e Programação Linear.',
      topics: 'Definição de PO, Fases de um estudo em PO e Introdução a Programação Linear.',
      videos: [{ title: 'Aula completa', youtubeId: 'v5KRSzU2E4U' }],
      materials: [] },
    { id: 'aula-2', number: 2, title: 'Aula 2: Teoria dos Grafos',
      description: 'Introdução à Teoria dos Grafos, seus conceitos fundamentais e aplicações em Pesquisa Operacional.',
      topics: 'Grafos, Vértices, Arestas, Grafos dirigidos e não dirigidos, Representações de grafos.',
      videos: [
        { title: 'Introdução a Teoria dos Grafos', youtubeId: 'MCFquBRoo_Y' },
        { title: 'Teoria dos Grafos - Parte 1', youtubeId: 'ucx_eZKsoRQ' },
        { title: 'Teoria dos Grafos - Parte 2', youtubeId: 'brfBvQO5MII' },
        { title: 'Gabarito Comentado', youtubeId: '_Ue2i2xdUVE' },
      ],
      materials: [
        { title: 'Slides - Grafos: Introdução', url: '/materiais/po2/grafos-introducao.pptx' },
        { title: 'Slides - Grafos Parte 1', url: '/materiais/po2/grafos-parte-1.pptx' },
        { title: 'Slides - Grafos Parte 2', url: '/materiais/po2/grafos-parte-2.pptx' },
      ] },
    { id: 'aula-3', number: 3, title: 'Aula 3: Árvore Geradora',
      description: 'Estudo das Árvores Geradoras Mínimas e dos principais algoritmos para sua obtenção.',
      topics: 'Árvores Geradoras Mínimas, Algoritmo de Kruskal, Algoritmo de Prim.',
      videos: [
        { title: 'Árvore Geradora - Introdução', youtubeId: 'WHxwUZNYqlE' },
        { title: 'Algoritmo de Kruskal', youtubeId: 'gQZ3hape028' },
        { title: 'Algoritmo de Prim', youtubeId: 'SoGAjtPReOc' },
      ],
      materials: [{ title: 'Slides - Árvores Geradoras Mínimas', url: '/materiais/po2/arvores-geradoras-minimas.pptx' }] },
    { id: 'aula-4', number: 4, title: 'Aula 4: Problema do Menor Caminho',
      description: 'Estudo do Problema do Menor Caminho e aplicação do Algoritmo de Dijkstra na teoria e na prática.',
      topics: 'Problema do Menor Caminho, Algoritmo de Dijkstra, Aplicações em redes.',
      videos: [
        { title: 'Menor Caminho - Teoria', youtubeId: 'Kr-32NTXZuM' },
        { title: 'Menor Caminho - Algoritmo e Prática', youtubeId: '1i1I5FNpW64' },
      ],
      materials: [
        { title: 'Slides - Dijkstra: Teoria', url: '/materiais/po2/dijkstra-teoria.pptx' },
        { title: 'Slides - Dijkstra: Prática', url: '/materiais/po2/dijkstra-pratica.pptx' },
      ] },
    { id: 'aula-5', number: 5, title: 'Aula 5: Problema do Fluxo Máximo',
      description: 'Estudo do Problema do Fluxo Máximo em redes e sua resolução prática.',
      topics: 'Fluxo Máximo, Redes de fluxo, Algoritmo Ford-Fulkerson.',
      videos: [
        { title: 'Fluxo Máximo - Teoria', youtubeId: 'UinUWIBy5pk' },
        { title: 'Fluxo Máximo - Prática', youtubeId: 'TP5sj-NIkqA' },
      ],
      materials: [] },
    { id: 'aula-6', number: 6, title: 'Aula 6: Problema do Fluxo de Custo Mínimo',
      description: 'Estudo do Problema do Fluxo de Custo Mínimo em redes de otimização.',
      topics: 'Fluxo de Custo Mínimo, Otimização em Redes, Modelos de fluxo.',
      videos: [{ title: 'Aula completa', youtubeId: 'pzZ29vszzpU' }],
      materials: [
        { title: 'Slides - Otimização em Redes', url: '/materiais/po2/otimizacao-em-redes.pptx' },
        { title: 'Slides - Otimização em Redes (Nova Versão)', url: '/materiais/po2/otimizacao-em-redes-nova-versao.pptx' },
      ] },
    { id: 'aula-7', number: 7, title: 'Aula 7: PERT e CPM',
      description: 'Técnicas de gerenciamento de projetos com foco em PERT e CPM para planejamento e controle de atividades.',
      topics: 'PERT, CPM, Caminho Crítico, Gerenciamento de Projetos, Redes de atividades.',
      videos: [],
      materials: [{ title: 'Slides - PERT e CPM', url: '/materiais/po2/pert-cpm.pptx' }] },
    { id: 'aula-8', number: 8, title: 'Aula 8: Teoria dos Jogos',
      description: 'Introdução à Teoria dos Jogos e seus modelos de tomada de decisão em situações de conflito.',
      topics: 'Teoria dos Jogos, Jogos de soma zero, Estratégias puras e mistas, Equilíbrio de Nash.',
      videos: [
        { title: 'Teoria dos Jogos - Parte 1', youtubeId: 'qaNQgtXEcuw' },
        { title: 'Teoria dos Jogos - Parte 2', youtubeId: 'Manxof9wOHE' },
        { title: 'Teoria dos Jogos - Parte 3', youtubeId: '9eqoxsfNc-E' },
      ],
      materials: [{ title: 'Slides - Teoria dos Jogos', url: '/materiais/po2/teoria-dos-jogos.pptx' }] },
    { id: 'aula-9', number: 9, title: 'Aula 9: Programação Inteira',
      description: 'Estudo dos modelos e métodos de resolução de problemas de Programação Inteira, incluindo o Algoritmo Branch and Bound.',
      topics: 'Programação Inteira, Modelos de PI, Algoritmo Branch and Bound, Aplicações.',
      videos: [
        { title: 'Programação Inteira - Parte 1', youtubeId: 'WZDdKfCHDzU' },
        { title: 'Programação Inteira - Parte 2', youtubeId: 'omPq4A__ujI' },
        { title: 'Programação Inteira - Parte 3', youtubeId: 'CqOF1SoOATQ' },
        { title: 'Branch and Bound - Prática', youtubeId: '0ym2EcCLfWc' },
      ],
      materials: [{ title: 'Slides - Programação Inteira', url: '/materiais/po2/programacao-inteira.pptx' }] },
    { id: 'aula-10', number: 10, title: 'Aula 10: Programação Não Linear',
      description: 'Estudo dos conceitos e métodos de resolução de problemas de Programação Não Linear.',
      topics: 'Programação Não Linear, Modelos de PNL, Condições de otimalidade, Métodos de resolução.',
      videos: [{ title: 'Aula completa', youtubeId: '97jdCupjz-0' }],
      materials: [{ title: 'Slides - Programação Não Linear', url: '/materiais/po2/programacao-nao-linear.pptx' }] },
  ],
}
